import mongoose from 'mongoose';
import { config } from './env';
import { User } from '../models/User';
import { Restaurant } from '../models/Restaurant';
import { RestaurantStaff } from '../models/RestaurantStaff';
import { MenuCategory } from '../models/MenuCategory';
import { MenuItem } from '../models/MenuItem';
import { RestaurantTable } from '../models/RestaurantTable';
import { Coupon } from '../models/Coupon';
import { RewardAccount } from '../models/RewardAccount';
import { RewardVoucher } from '../models/RewardVoucher';
import { Order } from '../models/Order';
import { Invoice } from '../models/Invoice';
import { Delivery } from '../models/Delivery';
import { Review } from '../models/Review';
import { generateInvoiceNumber, generateOrderNumber, generateSecureToken, generateVoucherCode } from '../utils/qr';

export const seedDatabase = async (): Promise<void> => {
  try {
    console.log('[Seed] Connecting to MongoDB...');
    await mongoose.connect(config.mongoUri);
    console.log('[Seed] Connected. Clearing existing collections...');

    await Promise.all([
      User.deleteMany({}),
      Restaurant.deleteMany({}),
      RestaurantStaff.deleteMany({}),
      MenuCategory.deleteMany({}),
      MenuItem.deleteMany({}),
      RestaurantTable.deleteMany({}),
      Coupon.deleteMany({}),
      RewardAccount.deleteMany({}),
      RewardVoucher.deleteMany({}),
      Order.deleteMany({}),
      Invoice.deleteMany({}),
      Delivery.deleteMany({}),
      Review.deleteMany({}),
    ]);

    console.log('[Seed] Seeding Users with clean role designations...');
    const customerUser = await User.create({
      name: 'Customer 1',
      email: 'customer@essen.com',
      phone: '9876543210',
      password: 'password123',
      role: 'customer',
      preferences: { foodType: 'any', favoriteCuisines: ['North Indian', 'Biryani', 'Italian'], spicinessPreference: 'spicy' },
      addresses: [
        { id: 'addr_1', title: 'Home', street: '42 Marina Bay View', city: 'Chennai', state: 'Tamil Nadu', pincode: '600004', isDefault: true },
        { id: 'addr_2', title: 'Office', street: 'Tech Park Tower B, OMR', city: 'Chennai', state: 'Tamil Nadu', pincode: '600096', isDefault: false },
      ],
    });

    const managerUser = await User.create({
      name: 'Manager 1',
      email: 'manager@essen.com',
      phone: '9876501234',
      password: 'password123',
      role: 'manager',
    });

    const waiterUser = await User.create({
      name: 'Employee 1',
      email: 'waiter@essen.com',
      phone: '9876512345',
      password: 'password123',
      role: 'waiter',
    });

    const driverUser = await User.create({
      name: 'Employee 2',
      email: 'driver@essen.com',
      phone: '9876523456',
      password: 'password123',
      role: 'delivery_partner',
    });

    const adminUser = await User.create({
      name: 'Admin 1',
      email: 'admin@essen.com',
      phone: '9876534567',
      password: 'admin123',
      role: 'admin',
    });

    console.log('[Seed] Seeding Premium Restaurants...');
    const restaurantsData = [
      {
        name: 'The Royal Nawabi Kitchen',
        slug: 'the-royal-nawabi-kitchen',
        restaurantCode: 'EST-ROY-1001',
        description: 'Heritage Awadhi and Mughal delicacies cooked in traditional slow dum pots with hand-ground spices.',
        tagline: 'Legacy of Royal Mughal & Awadhi Flavors',
        cuisine: ['North Indian', 'Mughlai', 'Biryani', 'Kebabs'],
        foodType: 'both',
        ambience: ['Fine Dining', 'Heritage', 'Family'],
        restaurantType: 'fine_dining',
        address: { street: '14 Khader Nawaz Khan Road', area: 'Nungambakkam', city: 'Chennai', state: 'Tamil Nadu', pincode: '600034' },
        location: { type: 'Point', coordinates: [80.2435, 13.0604] },
        contact: { phone: '044-28331122', email: 'nawabi@royalessen.com' },
        businessInfo: { gstin: '33AAACR1234F1Z1', fssaiLicense: '10019042004561' },
        images: {
          cover: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200',
          logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300',
          gallery: [
            'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
            'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
          ],
        },
        rating: 4.8,
        reviewCount: 420,
        averagePriceForTwo: 650,
        status: 'OPEN',
        isVerified: true,
        services: { dineIn: true, delivery: true, takeaway: true, tableBooking: true },
        rewardsSettings: {
          isEnabled: true,
          coinsPerOrderMin: 8,
          coinsPerOrderMax: 10,
          targetCoins: 5000,
          rewardTitle: 'Free Royal Nawabi Dum Feast Combo',
          rewardDescription: 'Exclusive 4-course royal feast featuring Murgh Dum Biryani, Galouti Kebabs, Roomali Roti, and Shahi Phirni.',
          comboItems: ['Royal Dum Biryani', 'Galouti Kebabs (4 pcs)', '2 Roomali Rotis', 'Shahi Saffron Phirni'],
        },
      },
      {
        name: 'Trattoria Bella Napoli',
        slug: 'trattoria-bella-napoli',
        restaurantCode: 'EST-BEL-2002',
        description: 'Authentic wood-fired Neapolitan pizzas, handmade fresh artisanal pasta, and Tuscan wines.',
        tagline: 'Woodfired Italian Perfection',
        cuisine: ['Italian', 'Pizza', 'Pasta', 'European'],
        foodType: 'both',
        ambience: ['Casual', 'Romantic', 'Outdoor'],
        restaurantType: 'cafe',
        address: { street: '28 Chamiers Road', area: 'R.A. Puram', city: 'Chennai', state: 'Tamil Nadu', pincode: '600028' },
        location: { type: 'Point', coordinates: [80.2522, 13.0245] },
        contact: { phone: '044-24358899', email: 'ciao@bellanapoli.com' },
        businessInfo: { gstin: '33AABCT9876E1Z5', fssaiLicense: '10019042004562' },
        images: {
          cover: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200',
          logo: 'https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=300',
          gallery: [],
        },
        rating: 4.7,
        reviewCount: 310,
        averagePriceForTwo: 550,
        status: 'OPEN',
        isVerified: true,
        services: { dineIn: true, delivery: true, takeaway: true, tableBooking: true },
        rewardsSettings: {
          isEnabled: true,
          coinsPerOrderMin: 6,
          coinsPerOrderMax: 10,
          targetCoins: 5000,
          rewardTitle: 'Free Woodfired Gourmet Pizza & Tiramisu Combo',
          rewardDescription: '12-inch artisanal sourdough pizza paired with classic espresso mascarpone tiramisu.',
          comboItems: ['12-inch Woodfired Margherita', 'Classic Tiramisu', 'Peach Iced Tea'],
        },
      },
      {
        name: 'Sattvam Pure Vegetarian Haven',
        slug: 'sattvam-pure-vegetarian-haven',
        restaurantCode: 'EST-SAT-3003',
        description: 'Pure satvic gourmet vegetarian feast prepared with farm-fresh organic produce and clarified butter.',
        tagline: 'Pure Satvic Gourmet Dining',
        cuisine: ['South Indian', 'North Indian', 'Pure Veg', 'Healthy'],
        foodType: 'pure-veg',
        ambience: ['Family', 'Peaceful', 'Traditional'],
        restaurantType: 'family',
        address: { street: '55 TTK Road', area: 'Alwarpet', city: 'Chennai', state: 'Tamil Nadu', pincode: '600018' },
        location: { type: 'Point', coordinates: [80.2514, 13.0338] },
        contact: { phone: '044-24997788', email: 'contact@sattvam.com' },
        businessInfo: { gstin: '33AADCS5544K1Z3', fssaiLicense: '10019042004563' },
        images: {
          cover: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200',
          logo: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=300',
          gallery: [],
        },
        rating: 4.9,
        reviewCount: 560,
        averagePriceForTwo: 350,
        status: 'OPEN',
        isVerified: true,
        services: { dineIn: true, delivery: true, takeaway: true, tableBooking: true },
        rewardsSettings: {
          isEnabled: true,
          coinsPerOrderMin: 5,
          coinsPerOrderMax: 8,
          targetCoins: 5000,
          rewardTitle: 'Free Royal Sattvam Grand Thali Combo',
          rewardDescription: 'An opulent 14-dish satvic thali with paneer makhani, dal makhani, stuffed kulchas, and saffron kheer.',
          comboItems: ['Grand Sattvam Thali', 'Saffron Rabdi', 'Dry Fruit Lassi'],
        },
      },
      {
        name: 'Tokyo Blossom Ramen & Izakaya',
        slug: 'tokyo-blossom-ramen',
        restaurantCode: 'EST-TOK-4004',
        description: 'Rich 18-hour slow simmered broths, handmade bouncy ramen noodles, gyoza, and Japanese yakitori.',
        tagline: 'Artisanal Ramen & Japanese Izakaya',
        cuisine: ['Japanese', 'Asian', 'Ramen', 'Sushi'],
        foodType: 'both',
        ambience: ['Modern', 'Cozy', 'Casual'],
        restaurantType: 'cafe',
        address: { street: '18 Gandhi Nagar 2nd Main', area: 'Adyar', city: 'Chennai', state: 'Tamil Nadu', pincode: '600020' },
        location: { type: 'Point', coordinates: [80.2554, 13.0067] },
        contact: { phone: '044-24419900', email: 'tokyo@blossom.com' },
        businessInfo: { gstin: '33AABCT3322P1Z8', fssaiLicense: '10019042004564' },
        images: {
          cover: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=1200',
          logo: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=300',
          gallery: [],
        },
        rating: 4.6,
        reviewCount: 280,
        averagePriceForTwo: 600,
        status: 'OPEN',
        isVerified: true,
        services: { dineIn: true, delivery: true, takeaway: true, tableBooking: true },
        rewardsSettings: {
          isEnabled: true,
          coinsPerOrderMin: 7,
          coinsPerOrderMax: 10,
          targetCoins: 5000,
          rewardTitle: 'Free Signature Spicy Miso Ramen & Crispy Gyoza Combo',
          rewardDescription: 'Our bestselling spicy miso ramen paired with pan-fried chicken gyoza and Japanese matcha iced tea.',
          comboItems: ['Spicy Miso Ramen', 'Crispy Gyoza (6 pcs)', 'Matcha Green Iced Tea'],
        },
      },
    ];

    const createdRestaurants = await Restaurant.create(restaurantsData);
    const primaryRest = createdRestaurants[0]; // The Royal Nawabi Kitchen

    console.log('[Seed] Binding Manager and Waiter to primary restaurant...');
    await RestaurantStaff.create([
      {
        user: managerUser._id,
        restaurant: primaryRest._id,
        staffRole: 'manager',
        employeeCode: 'MGR-001',
        assignedTables: [1, 2, 3, 4, 5, 6],
      },
      {
        user: waiterUser._id,
        restaurant: primaryRest._id,
        staffRole: 'waiter',
        employeeCode: 'WTR-101',
        assignedTables: [1, 2, 3, 4],
      },
    ]);

    console.log('[Seed] Seeding Tables for each restaurant...');
    for (const rest of createdRestaurants) {
      const tableConfigs = [
        { tableNumber: 1, tableName: 'Table 1 - Window Side', capacity: 2, section: 'indoor' },
        { tableNumber: 2, tableName: 'Table 2 - Center Cozy', capacity: 4, section: 'indoor' },
        { tableNumber: 3, tableName: 'Table 3 - Royal Family Booth', capacity: 6, section: 'indoor' },
        { tableNumber: 4, tableName: 'Table 4 - Terrace Star View', capacity: 4, section: 'rooftop' },
        { tableNumber: 5, tableName: 'Table 5 - Private Dining Room', capacity: 8, section: 'private_dining' },
      ];

      for (const t of tableConfigs) {
        await RestaurantTable.create({
          restaurant: rest._id,
          tableNumber: t.tableNumber,
          tableName: t.tableName,
          capacity: t.capacity,
          section: t.section as any,
          status: t.tableNumber === 2 ? 'OCCUPIED' : 'AVAILABLE',
          qrToken: generateSecureToken(`TBL_${rest._id}_${t.tableNumber}`),
        });
      }
    }

    console.log('[Seed] Seeding Menu Categories and Dishes...');
    const nawabiCategories = await MenuCategory.create([
      { restaurant: primaryRest._id, name: 'Royal Dum Biryanis', sortOrder: 1 },
      { restaurant: primaryRest._id, name: 'Signature Kebabs & Starters', sortOrder: 2 },
      { restaurant: primaryRest._id, name: 'Rich Curries & Gravies', sortOrder: 3 },
      { restaurant: primaryRest._id, name: 'Artisanal Breads', sortOrder: 4 },
      { restaurant: primaryRest._id, name: 'Royal Desserts & Beverages', sortOrder: 5 },
    ]);

    const nawabiDishes = [
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[0]._id,
        name: 'Royal Awadhi Murgh Dum Biryani',
        description: 'Tender succulent chicken marinated in saffron, rose water, and 24 royal spices, dum cooked with aged basmati rice.',
        price: 280,
        foodType: 'non-vegetarian',
        tasteProfile: 'spicy',
        cuisine: 'North Indian',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 840,
        preparationTimeMinutes: 25,
        customizationGroups: [
          {
            name: 'Portion Size',
            type: 'single',
            isRequired: true,
            options: [
              { name: 'Regular (Serves 1)', price: 0 },
              { name: 'Large (Serves 2)', price: 150 },
            ],
          },
          {
            name: 'Spice Level',
            type: 'single',
            isRequired: false,
            options: [
              { name: 'Medium Spicy', price: 0 },
              { name: 'Extra Royal Spicy', price: 0 },
            ],
          },
          {
            name: 'Add-ons',
            type: 'multiple',
            isRequired: false,
            options: [
              { name: 'Extra Boiled Egg', price: 25 },
              { name: 'Extra Mirchi Ka Salan', price: 30 },
              { name: 'Burani Garlic Raita', price: 40 },
            ],
          },
        ],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[0]._id,
        name: 'Subz Nizami Saffron Biryani',
        description: 'Seasonal baby vegetables, paneer cubes, and golden raisins layered with fragrant saffron basmati rice.',
        price: 240,
        foodType: 'vegetarian',
        tasteProfile: 'mild',
        cuisine: 'North Indian',
        image: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=800',
        isTrending: true,
        isBestseller: false,
        rating: 4.8,
        orderCount: 420,
        preparationTimeMinutes: 20,
        customizationGroups: [
          {
            name: 'Add-ons',
            type: 'multiple',
            isRequired: false,
            options: [
              { name: 'Extra Paneer Cubes (4 pcs)', price: 50 },
              { name: 'Pomegranate Mint Raita', price: 40 },
            ],
          },
        ],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[1]._id,
        name: 'Melt-in-Mouth Galouti Kebabs',
        description: 'Finely minced spiced mutton patties infused with raw papaya and aromatic spices, shallow pan seared in pure desi ghee.',
        price: 290,
        foodType: 'non-vegetarian',
        tasteProfile: 'spicy',
        cuisine: 'Mughlai',
        image: '/images/dishes/galouti-kebab.jpg',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 650,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[2]._id,
        name: 'Paneer Lababdar Special',
        description: 'Fresh cottage cheese batons tossed in a rich cashew onion tomato gravy finished with butter and dried fenugreek.',
        price: 260,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'North Indian',
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800',
        isTrending: false,
        isBestseller: true,
        rating: 4.7,
        orderCount: 390,
        preparationTimeMinutes: 20,
        customizationGroups: [],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[3]._id,
        name: 'Butter Garlic Naan & Roomali Combo',
        description: 'Tandoor charred garlic butter naan accompanied by a soft hand-stretched roomali roti.',
        price: 75,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'North Indian',
        image: '/images/dishes/garlic-naan.jpg',
        isTrending: false,
        isBestseller: false,
        rating: 4.8,
        orderCount: 500,
        preparationTimeMinutes: 10,
        customizationGroups: [],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[4]._id,
        name: 'Shahi Saffron Phirni in Clay Pot',
        description: 'Slow-cooked ground rice pudding flavored with green cardamom, Kashmiri saffron, pistachios, and silver vark.',
        price: 110,
        foodType: 'vegetarian',
        tasteProfile: 'sweet',
        cuisine: 'Mughlai',
        image: '/images/dishes/shahi-phirni.jpg',
        isTrending: false,
        isBestseller: true,
        rating: 4.9,
        orderCount: 480,
        preparationTimeMinutes: 5,
        customizationGroups: [],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[1]._id,
        name: 'Tandoori Seekh Kebab Shahi',
        description: 'Spiced minced lamb infused with fresh coriander, mint, ginger, and roasted cumin, skewered and charred over flaming tandoor coals.',
        price: 270,
        foodType: 'non-vegetarian',
        tasteProfile: 'spicy',
        cuisine: 'Mughlai',
        image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        isTrending: false,
        isBestseller: true,
        rating: 4.8,
        orderCount: 510,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: primaryRest._id,
        category: nawabiCategories[1]._id,
        name: 'Paneer Tikka Angara',
        description: 'Cubes of fresh malai paneer steeped in mustard oil, ajwain, and Kashmiri red chili marinade, glazed with butter in charcoal oven.',
        price: 240,
        foodType: 'vegetarian',
        tasteProfile: 'spicy',
        cuisine: 'North Indian',
        image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800',
        isTrending: true,
        isBestseller: false,
        rating: 4.8,
        orderCount: 380,
        preparationTimeMinutes: 12,
        customizationGroups: [],
      },
    ];

    const createdNawabiDishes = await MenuItem.create(nawabiDishes);

    // 2. Trattoria Bella Napoli Dishes
    const bellaCategories = await MenuCategory.create([
      { restaurant: createdRestaurants[1]._id, name: 'Woodfired Pizzas', sortOrder: 1 },
      { restaurant: createdRestaurants[1]._id, name: 'Handmade Pasta', sortOrder: 2 },
      { restaurant: createdRestaurants[1]._id, name: 'Appetizers & Insalata', sortOrder: 3 },
      { restaurant: createdRestaurants[1]._id, name: 'Artisanal Desserts', sortOrder: 4 },
    ]);

    await MenuItem.create([
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[0]._id,
        name: 'Quattro Formaggi & Truffle Pizza',
        description: 'San Marzano tomato base, fresh buffalo mozzarella, gorgonzola, parmesan, fontina, and black truffle oil drizzle.',
        price: 380,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Italian',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.8,
        orderCount: 380,
        preparationTimeMinutes: 18,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[0]._id,
        name: 'Margherita Classica di Bufala',
        description: 'Crushed sweet San Marzano tomatoes, fresh creamy buffalo mozzarella, sweet Italian basil leaves, and cold-pressed olive oil.',
        price: 320,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Italian',
        image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800',
        isTrending: false,
        isBestseller: true,
        rating: 4.9,
        orderCount: 620,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[0]._id,
        name: 'Spicy Diavola Pepperoni Pizza',
        description: 'Signature crispy sourdough crust topped with spicy artisanal salami, pickled jalapenos, chili honey drizzle, and mozzarella.',
        price: 410,
        foodType: 'non-vegetarian',
        tasteProfile: 'spicy',
        cuisine: 'Italian',
        image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.8,
        orderCount: 440,
        preparationTimeMinutes: 18,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[1]._id,
        name: 'Spicy Arrabbiata Penne',
        description: 'Penne pasta tossed in a fiery garlic chili San Marzano tomato sauce with fresh basil and extra virgin olive oil.',
        price: 260,
        foodType: 'vegan',
        tasteProfile: 'spicy',
        cuisine: 'Italian',
        image: '/images/dishes/penne-arrabbiata.jpg',
        isTrending: true,
        isBestseller: false,
        rating: 4.7,
        orderCount: 290,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[1]._id,
        name: 'Truffle Fettuccine Al Funghi',
        description: 'Fresh ribbon pasta folded in a velvet butter emulsion of wild porcini mushrooms, black summer truffle paste, and Parmigiano Reggiano.',
        price: 340,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Italian',
        image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 350,
        preparationTimeMinutes: 16,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[2]._id,
        name: 'Artisanal Bruschetta al Pomodoro',
        description: 'Grilled crusty Italian sourdough rubbed with fresh garlic, topped with heirloom cherry tomatoes, cold-pressed olive oil, and aged balsamic glaze.',
        price: 180,
        foodType: 'vegan',
        tasteProfile: 'savory',
        cuisine: 'Italian',
        image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
        isTrending: false,
        isBestseller: false,
        rating: 4.7,
        orderCount: 210,
        preparationTimeMinutes: 10,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[1]._id,
        category: bellaCategories[3]._id,
        name: 'Classic Espresso Mascarpone Tiramisu',
        description: 'Traditional Italian savoiardi ladyfingers soaked in dark roast espresso, layered with whipped sweet mascarpone cream and dusted with Valrhona cocoa.',
        price: 190,
        foodType: 'vegetarian',
        tasteProfile: 'sweet',
        cuisine: 'Italian',
        image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 480,
        preparationTimeMinutes: 5,
        customizationGroups: [],
      },
    ]);

    // 3. Sattvam Pure Vegetarian Haven Dishes
    const sattvamCategories = await MenuCategory.create([
      { restaurant: createdRestaurants[2]._id, name: 'Satvic Gourmet Thalis', sortOrder: 1 },
      { restaurant: createdRestaurants[2]._id, name: 'Pure Desi Ghee Curries', sortOrder: 2 },
      { restaurant: createdRestaurants[2]._id, name: 'South Indian Specialties', sortOrder: 3 },
      { restaurant: createdRestaurants[2]._id, name: 'Satvic Sweets & Coolers', sortOrder: 4 },
    ]);

    await MenuItem.create([
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[0]._id,
        name: 'Grand Sattvam Maharaja Thali',
        description: 'An opulent 14-dish satvic feast: Paneer Makhanwala, Slow-cooked Dal Makhani, Subz Panchmel, Steamed Basmati, 2 Desi Ghee Phulkas, Saffron Rabdi, and Kesar Lassi.',
        price: 350,
        foodType: 'vegetarian',
        tasteProfile: 'mild',
        cuisine: 'Pure Veg',
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 780,
        preparationTimeMinutes: 20,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[1]._id,
        name: 'Paneer Makhanwala in Desi Ghee',
        description: 'Soft cottage cheese simmered in a silky tomato cashew gravy made without onion or garlic, finished with pure cow ghee and fragrant kasuri methi.',
        price: 250,
        foodType: 'vegetarian',
        tasteProfile: 'mild',
        cuisine: 'North Indian',
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800',
        isTrending: false,
        isBestseller: true,
        rating: 4.8,
        orderCount: 410,
        preparationTimeMinutes: 18,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[1]._id,
        name: 'Slow Cooked Dal Makhani',
        description: 'Whole black lentils and kidney beans slow simmered for 16 hours over low charcoal heat, infused with churned butter and mild spices.',
        price: 210,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'North Indian',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.8,
        orderCount: 520,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[2]._id,
        name: 'Crispy Ghee Roast Masala Dosa',
        description: 'Golden, paper-crisp fermented rice-lentil crepe smeared with aromatic pure ghee, stuffed with spiced tempered potato masala, served with 3 fresh chutneys.',
        price: 160,
        foodType: 'vegetarian',
        tasteProfile: 'savory',
        cuisine: 'South Indian',
        image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 890,
        preparationTimeMinutes: 12,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[2]._id,
        name: 'Malabar Coconut Vegetable Stew with Appam',
        description: 'Baby carrots, green peas, and shallots simmered in fragrant spiced coconut milk with whole spices, served with two fluffy lacy fermented appams.',
        price: 230,
        foodType: 'vegan',
        tasteProfile: 'mild',
        cuisine: 'South Indian',
        image: '/images/dishes/appam-stew.jpg',
        isTrending: false,
        isBestseller: false,
        rating: 4.7,
        orderCount: 260,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[3]._id,
        name: 'Saffron Pistachio Rabdi & Malpua',
        description: 'Crispy sweet fennel-infused pancakes soaked in aromatic sugar syrup, topped with thick condensed rabdi, silver leaf, and sliced Iranian pistachios.',
        price: 140,
        foodType: 'vegetarian',
        tasteProfile: 'sweet',
        cuisine: 'Pure Veg',
        image: '/images/dishes/rabdi-malpua.jpg',
        isTrending: false,
        isBestseller: true,
        rating: 4.9,
        orderCount: 390,
        preparationTimeMinutes: 5,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[2]._id,
        category: sattvamCategories[3]._id,
        name: 'Kesar Dry Fruit Chilled Lassi',
        description: 'Thick hand-churned sweet curd beverage infused with saffron strands, crushed almonds, cashews, and a dollop of fresh clotted malai.',
        price: 110,
        foodType: 'vegetarian',
        tasteProfile: 'sweet',
        cuisine: 'Pure Veg',
        image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=800',
        isTrending: false,
        isBestseller: true,
        rating: 4.8,
        orderCount: 610,
        preparationTimeMinutes: 5,
        customizationGroups: [],
      },
    ]);

    // 4. Tokyo Blossom Ramen & Izakaya Dishes
    const tokyoCategories = await MenuCategory.create([
      { restaurant: createdRestaurants[3]._id, name: 'Signature Ramen Bowls', sortOrder: 1 },
      { restaurant: createdRestaurants[3]._id, name: 'Izakaya Small Plates & Gyoza', sortOrder: 2 },
      { restaurant: createdRestaurants[3]._id, name: 'Sushi & Donburi', sortOrder: 3 },
      { restaurant: createdRestaurants[3]._id, name: 'Japanese Drinks & Desserts', sortOrder: 4 },
    ]);

    await MenuItem.create([
      {
        restaurant: createdRestaurants[3]._id,
        category: tokyoCategories[0]._id,
        name: 'Signature Spicy Miso Ramen',
        description: 'Rich 18-hour slow simmered broth with fermented red miso, springy handmade noodles, tender chashu, soft molten ajitsuke egg, menma, and roasted nori.',
        price: 340,
        foodType: 'non-vegetarian',
        tasteProfile: 'spicy',
        cuisine: 'Japanese',
        image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 680,
        preparationTimeMinutes: 18,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[3]._id,
        category: tokyoCategories[0]._id,
        name: 'Creamy Black Garlic Tonkotsu Ramen',
        description: 'Ultra-creamy rich pork broth infused with charred black garlic oil (mayu), topped with seared pork belly, wood ear mushrooms, and scallions.',
        price: 360,
        foodType: 'non-vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Japanese',
        image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.8,
        orderCount: 540,
        preparationTimeMinutes: 18,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[3]._id,
        category: tokyoCategories[1]._id,
        name: 'Crispy Pan-Fried Chicken Gyoza',
        description: 'Six delicate handmade dumplings filled with spiced ground chicken and scallions, seared with a crisp lace skirt, served with chili citrus ponzu dip.',
        price: 220,
        foodType: 'non-vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Japanese',
        image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800',
        isTrending: true,
        isBestseller: true,
        rating: 4.7,
        orderCount: 490,
        preparationTimeMinutes: 12,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[3]._id,
        category: tokyoCategories[2]._id,
        name: 'Crunchy Tempura & Avocado Roll (8 pcs)',
        description: 'Golden crunchy tiger prawn tempura and ripe hass avocado rolled with vinegared sushi rice, sesame seeds, and sweet unagi drizzle.',
        price: 360,
        foodType: 'non-vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Japanese',
        image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
        isTrending: true,
        isBestseller: false,
        rating: 4.8,
        orderCount: 370,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[3]._id,
        category: tokyoCategories[2]._id,
        name: 'Teriyaki Chicken Donburi Bowl',
        description: 'Grilled juicy chicken thighs glazed in house-brewed sweet soy mirin teriyaki glaze over steamed Koshihikari rice with sesame greens.',
        price: 280,
        foodType: 'non-vegetarian',
        tasteProfile: 'savory',
        cuisine: 'Japanese',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        isTrending: false,
        isBestseller: true,
        rating: 4.7,
        orderCount: 320,
        preparationTimeMinutes: 15,
        customizationGroups: [],
      },
      {
        restaurant: createdRestaurants[3]._id,
        category: tokyoCategories[3]._id,
        name: 'Japanese Uji Matcha Basque Cheesecake',
        description: 'Velvety burnt Basque-style cheesecake infused with ceremonial grade Uji green tea powder, served with sweet red azuki bean compote.',
        price: 190,
        foodType: 'vegetarian',
        tasteProfile: 'sweet',
        cuisine: 'Japanese',
        image: '/images/dishes/matcha-cheesecake.jpg',
        isTrending: true,
        isBestseller: true,
        rating: 4.9,
        orderCount: 410,
        preparationTimeMinutes: 5,
        customizationGroups: [],
      },
    ]);

    console.log('[Seed] Seeding Coupons & Promotions...');
    await Coupon.create([
      {
        code: 'ESSEN50',
        title: '50% OFF up to ₹150',
        description: 'Get 50% discount on orders above ₹200 across all partner dining spots.',
        discountType: 'percentage',
        discountValue: 50,
        minOrderValue: 200,
        maxDiscountAmount: 150,
        applicableOrderTypes: ['online', 'dine_in'],
        expiryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
      {
        code: 'WELCOME20',
        title: 'Flat ₹100 OFF',
        description: 'Flat ₹100 discount on your first online order.',
        discountType: 'fixed',
        discountValue: 100,
        minOrderValue: 300,
        maxDiscountAmount: 100,
        applicableOrderTypes: ['online'],
        expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
    ]);

    console.log('[Seed] Seeding Fresh Customer Reward Accounts (0 Coins Initial Balance)...');
    await RewardAccount.create({
      customer: customerUser._id,
      restaurant: primaryRest._id,
      coinBalance: 0,
      lifetimeCoinsEarned: 0,
      lifetimeCoinsRedeemed: 0,
      tier: 'BRONZE',
    });

    await RewardAccount.create({
      customer: customerUser._id,
      restaurant: createdRestaurants[1]._id,
      coinBalance: 0,
      lifetimeCoinsEarned: 0,
      lifetimeCoinsRedeemed: 0,
      tier: 'BRONZE',
    });

    console.log('[Seed] Seeding Completed Successfully! Fresh platform initialized with 0 coins.');
    process.exit(0);
  } catch (error) {
    console.error('[Seed Error]:', error);
    process.exit(1);
  }
};

if (require.main === module) {
  seedDatabase();
}
